
import { UseCase } from './types';

export const USE_CASES: UseCase[] = [
  {
    id: "1",
    faculty: "Caitlin",
    categories: ["Course Content Development", "Examples and Illustrations"],
    title: "Finding Example Systems and Histories",
    description: "Finding example systems and their histories that go along with different models of human behavior. It's been helpful to identify systems that explicitly addressed certain issues and one or two pointers to references. Then, I expand from there.",
    tags: ["examples", "research", "course-content"]
  },
  {
    id: "2",
    faculty: "Marcus",
    categories: ["Assessment & Feedback"],
    title: "Generating Rubrics for Creative Writing",
    description: "Using LLMs to generate initial drafts of grading rubrics for subjective assignments. This helps standardize feedback while ensuring specific learning outcomes are addressed in creative projects.",
    tags: ["grading", "rubrics", "creative-writing"]
  },
  {
    id: "3",
    faculty: "Sarah",
    categories: ["Lesson Planning", "Interactive Learning"],
    title: "AI Socratic Tutor for Philosophy",
    description: "Setting up a custom GPT to act as a Socratic interlocutor for students. It helps them refine their philosophical arguments before coming to class for live discussions.",
    tags: ["philosophy", "critical-thinking", "tutoring"]
  },
  {
    id: "4",
    faculty: "David",
    categories: ["Administrative", "Course Content Development"],
    title: "Syllabus Policy Drafting",
    description: "Generating first drafts for AI usage policies in different courses, ranging from 'AI-forbidden' to 'AI-encouraged' scenarios to set clear expectations for students.",
    tags: ["policy", "syllabus", "ethics"]
  },
  {
    id: "5",
    faculty: "Elena",
    categories: ["Examples and Illustrations"],
    title: "Complex Visualization Prompts",
    description: "Creating complex data visualization examples using Python generated by AI. This allows me to show students high-level visual representations of data sets that would have taken hours to code manually.",
    tags: ["data-viz", "python", "coding"]
  },
  {
    id: "6",
    faculty: "Jordan",
    categories: ["Interactive Learning"],
    title: "Role-Playing Historical Figures",
    description: "Students interact with a GenAI persona acting as a historical figure like Machiavelli or Mary Wollstonecraft to test their understanding of the author's primary texts.",
    tags: ["history", "roleplay", "lit"]
  },
  {
    id: "7",
    faculty: "Caitlin",
    categories: ["Course Content Development"],
    title: "Flashcard Generation for Bio-Chem",
    description: "Converting lecture notes directly into high-quality flashcard sets for Anki. This saves students prep time and allows them to focus on active recall earlier in the semester.",
    tags: ["biology", "study-tools", "productivity"]
  },
  {
    id: "8",
    faculty: "Wei",
    categories: ["Assessment & Feedback"],
    title: "Language Translation & Nuance",
    description: "In advanced Mandarin courses, we use AI to translate idiomatic expressions and then critique the output's cultural accuracy as a class exercise.",
    tags: ["language", "translation", "culture"]
  }
];
